### ISSUE TITLE
pls give solution sir

### ISSUE THREAD

**Issue by bavan15** [MohitSojitra/e-commerce-store#2]
![Screenshot (310)](https://user-images.githubusercontent.com/110404839/195767045-5ef7534b-0159-437a-9ed5-76b934f0ac0d.png)

**Comment by MohitSojitra** [comment]
@bavan15 Thanks for reporting issue, as I check this on my machine this seems like api calling, Request is not send properly send to the backend. Please follow below step and try to re run project.


Step1:
- `cd e-comerce-backend`
- `yarn`
- `yarn data:import`
- create .env file and write on that `PORT=3000`
- `yarn dev`



Then go to frontend project
- `yarn`
- Then change the base url in config.js file to http://localhost:3000
- then `yarn start`

And Your project will start, And sorry for late response, and also I am updating this repo. 
Thanks
